### ISSUE TITLE
The Corporate name that holds copyrights should be HITSLab LLC (c) 2016

### ISSUE THREAD

**Issue by ptavolacci** [Hitslabs/hitslabs#10]
Currently the site shows at www.hitslabs.com/contact that hitslabs copyright 2016 but should list here and every other page footer as HITSLab LLC Copyright 2016

**Comment by skagels-hitslab** [comment]
Footer updated with proper Corporate name (main template affects all content pages). Also updated company name on About page.

**Comment by skagels-hitslab** [comment]
Deployed fix to production site. Fixed footer template and content on About Us pages

**Comment by ptavolacci** [comment]
Looks good as I see it in production now. Is this why it is on the dashboard under Review/QA?

**Comment by skagels-hitslab** [comment]
I deployed the fix last night. If you want I can assign Review or Done stories to you.

Sent from my iPhone
617.970.5231

**Comment by ptavolacci** [comment]
Scott, I'm not even sure this response gets to you but let's chat on
Tuesday about how we should configure Zenhub.

Thanks!

Paul

Paul M Tavolacci <https://www.linkedin.com/in/paul-tavolacci-mba-b4b0866>
Hitslab LLC
30 Hilton Street
Darien, CT 06820
415-595-4625 Direct
www.hitslabs.com

**Comment by skagels-hitslab** [comment]
Sure, no problem

Sent from my iPhone
617.970.5231

**Comment by skagels-hitslab** [comment]
@ptavolacci Paul, 
Just FYI to this ticket being in the Review/QA state/column. You don't have to take action on a ticket unless:
1. You're responding to question/comment
2. You have been assigned the ticket.

For example, I was just expecting to go over tickets in the Review column with you on Tuesday. We can certainly discuss a more formal process/expectation on Tuesday. It's a little weird working though the workflow with just 2 of us in the mix.  It will make more sense as we grow a team of people with more specialized responsibilities, e.g., more developers, QA tests, etc.  I hope that clarifies things a little. If not, as you said, let's discuss on Tuesday.
