### ISSUE TITLE
As an end user, I would like to register for a user account on www.hitslabs.com

### ISSUE THREAD

**Issue by skagels-hitslab** [Hitslabs/hitslabs#12]
Acceptance Criteria:
- [x] site header contains link to registration page (to the right of Contacts)
- [x] site hosts a User Registration page for users to request an account
- [x] include disclaimer that site is not secure right now, in alpha testing. enter data at own risk
- [ ] submit to User table (as disabled)
- [x] email is triggered to Paul that a new user has registered to review

**Comment by ptavolacci** [comment]
We should collect First Name, Last name, age- thresholds (minor or not, applies to COPA Regulations), Primary Address (#, Street, City, Town, Zip), E-mail address under which they want to operate. 

**Optional Data** should include place of business (legal name of entity, address where user most often reports for work). This data will be used to cross-sell to corporate wellness departments later in our development of the platform. 

**Required data** for Dog and Horse owners (established upon creating the animal's profile) should include name and city of veterinary practice most often used recently

**Optional data** for Dog and Horse owners (established upon creating the animal's profile) should include e-mail address of veterinary administration. This data can also be captured upon ad-hoc use of intake-forms and drive our prospecting process.

**Comment by ptavolacci** [comment]
This page should be able to serve advertisements in the right-hand third of the page like the one that Mohamed created for search. Use the same mask, layout

**Comment by ptavolacci** [comment]
Let's use Year of Birth rather than date of birth for this purpose. Since we do not have security in place this is personal information that should not be provided. YOB will let us know the age of anyone and give a determination of whether they are of age to participate in the best test as adults

**Comment by ptavolacci** [comment]
YOB selection should be in a drop-down that includes YOBs of minors up through older adults. We must demonstrate that we are preparing to handle authorization on the basis of age-eligibility

**Comment by skagels-hitslab** [comment]
Still to do:

- Use YOB instead of DOB
- Form Validation (all current fields are mandatory)
- admin page listing all pending registration requests (we need to lock down access to this page, quick fix with an access key in query string if necessary)
  - provide ability to authorize registration
  - filter requests by pending | authorized

- add request fields: date of submission
- add field for authorized by admin
- Beta testing content: We are looking for Beta Testers for this site. Request access to become a Beta Tester. 
- include disclaimer that site is not secure right now, in alpha testing. enter data at own risk
- submit to User table (as disabled)

-

**Comment by skagels-hitslab** [comment]
form validation: consider https://validatejs.org/

**Comment by skagels-hitslab** [comment]
@ptavolacci Paul,

I do not have admin rights to create a new hitslabs.com gmail account. But I think you do. Can you confirm/create a noreply@hitslabs.com account: 
Instructions: https://support.google.com/a/answer/33327?hl=en   

Once the account is created and I have the account credentials (username/password) then I can configure the site to use this user instead if the hitslabssender account. 

Thanks,
Scott

**Comment by ptavolacci** [comment]
@skagels-hitslab Scott,
I tried adding an e-mail account for $50/year today but this is apparently still managed by Wordpress. I don't want to inadvertantly renew anything for a year. It says the service (Google GSuite-the new name they use) renews on December 26th, 2016 when I go to the Google Admin Console and it bounces me back to Wordpress. See Screenshot below
![image](https://cloud.githubusercontent.com/assets/19537208/20246669/b6246892-a989-11e6-9663-24e347e5dcea.png)

**Comment by skagels-hitslab** [comment]
@ptavolacci Paul,

I deployed registration form enhancements to the production site this morning:
- [x] Use YOB instead of DOB
- [x] Form Validation (all current fields are mandatory)
- [x] add request fields: date of submission
- [x] add field for authorized by admin
- [x] Beta testing content: We are looking for Beta Testers for this site. Request access to become a Beta Tester.
- [x] include disclaimer that site is not secure right now, in alpha testing. enter data at own risk



Still to do:
- [ ]  change From Address to noreply@hitslabs.com for email notifications that are triggered off a submission
- [ ] admin page listing all pending registration requests (we need to lock down access to this page,        
  -   quick fix with an access key in query string if necessary)
  - provide ability to authorize registration
  - filter requests by pending | authorized
- [ ]  submit to User table (as disabled)

**Comment by ptavolacci** [comment]
noreply@hitslabs.com user was created on Google G Suite. Information was sent to Scott Kagels. Requested change of the First & Last Name Fields which are currently Scotty Kagels respectively

**Comment by ptavolacci** [comment]
Brian Nadzan registered himself and commented that he was able to register twice. Suggests that the confirm for registration disappears after a period of time and a different part of the site appears. Maybe the search page should appear once it's completed?

**Comment by skagels-hitslab** [comment]
This will be a good thing to discuss over lunch today...

We really need to back this with a database table so we can easily search against existing registrations (by email address) to prevent duplicate registrations. I just haven’t had the bandwidth to put that into place yet.

I’m not sure how much sense it makes for the confirmation message to just disappear. Maybe the confirmation message is displayed on a separate page (instead of in the modal) so that the user doesn’t see the form after a successful submission. 

-Scott
> On Nov 15, 2016, at 9:28 A

**Comment by bnadzan** [comment]
This was simply a UI workflow. After submitting the registration form, the page should switch to a different view.

**Comment by skagels-hitslab** [comment]
@ptavolacci 
noreply@hitslabs.com needs the following:
- Only admin can change First and Last Name of account
- Only admin can enable access to less secure apps - I think this is required to sent email from the production site.


Enhancements:
- [ ] Confirmation message should be on another page, so that user doesn't try to resubmit form. Would be nice to server ad on this page (we'll get that once ad panel is added to main layout) - (Add this is a new story)

**Comment by ptavolacci** [comment]
First and Last Name's associated with ID have been changed to Hitslab LLC and Administration respectively

**Comment by skagels-hitslab** [comment]
@ptavolacci I have added stories for the outstanding issues:
- hitslabs #61: Admin Page 
- hitslabs #62: Form Validation/Workflow 

This just leaves noreply@hitslabs.com access to less secure sites to be enabled, which looks like it must be done from the admin email account. This will allow the site to send emails from noreply account.

We should be able to close this story now unless there were other concerns you think we need to capture.

**Comment by ptavolacci** [comment]
Everything developed to date is working as expected here other than the submission to use table and beyond. What other reasons is it labeled for questioning?

**Comment by skagels-hitslab** [comment]
@ptavolacci I think it's safe to remove the question label.
