### ISSUE TITLE
Provide a confirmation message when clicking "Submit" on Contact Page

### ISSUE THREAD

**Issue by ptavolacci** [Hitslabs/hitslabs#28]
As a user it is unclear if I have sent my message to Hitslab LLC. http://www.hitslabs.com/contact currently does not provide a confirmation message that I have been successful. Please provide a means by which to confirm that the message has been sent. This will prevent flooding of ptavolacci@hitslabs.com and skagels@hitslabs.com to which it copies.

**Comment by skagels-hitslab** [comment]
Deployed confirmation message upon form submission to production site.

**Comment by ptavolacci** [comment]
Looks good! I have tested this.  Paul
