### ISSUE TITLE
As a User I am discouraged from using the Search page if it does not have a Disclaimer

### ISSUE THREAD

**Issue by ptavolacci** [Hitslabs/hitslabs#32]
http://www.hitslabs.com/search should have a message (across the screen in space above the purple bar?) that says:
"Coming soon- A search engine for specialists in animal and human health"

**Comment by ptavolacci** [comment]
This should be prioritized into the backlog next sprint

**Comment by skagels-hitslab** [comment]
@sanpinrin1 Mohamed, let's discuss details when we talk next week.

Thanks,
Scott

**Comment by skagels-hitslab** [comment]
@sanpinrin1 Please put the disclaimer in a div with the class: messageBox:
 <div class="messageBox"> ... </div>
