### ISSUE TITLE
As a user I would like the home page to lead me to understand the mission

### ISSUE THREAD

**Issue by ptavolacci** [Hitslabs/hitslabs#58]
As soon as Dan Ameri creates the viral advertisement to promote the animal health (dogs only) beta test, he will provide a link to the ~16 second spot. It should be posted on the home page next to the woman doctor with the text, "Join our beta test in animal health solutions. See xxx (link to video) or register directly at www.hitslabs.com/register"

**Comment by ptavolacci** [comment]
The video should be ready on Wednesday the 16th of November, most likely

**Comment by ptavolacci** [comment]
Reconfirmed that the video will be ready today

**Comment by skagels-hitslab** [comment]
@ptavolacci It's up there!!!

**Comment by ptavolacci** [comment]
Looks good and it works well. Will open another issue if we want to distribute the video separately from the website
