### ISSUE TITLE
As a visitor I'm impressed by full resolution pictures

### ISSUE THREAD

**Issue by ptavolacci** [Hitslabs/hitslabs#60]
Please replace the low grade picture on the homepage with https://drive.google.com/drive/folders/0B0uhgpO6Xg7tMDlQNDVDZVQ1RHc which is 3MBs large

**Comment by skagels-hitslab** [comment]
@ptavolacci This has been pushed to production. Please close this story or assign back to me with an issues.

Thanks,
Scott

**Comment by ptavolacci** [comment]
Looks great. Closing
