### ISSUE TITLE
Forbidden message appears on Advertising panel on all pages where advertisements show

### ISSUE THREAD

**Issue by ptavolacci** [Hitslabs/hitslabs#63]
See attached. Able to replicate on Desktop on Windows, IOS on Iphone 6

**Comment by skagels-hitslab** [comment]
@ptavolacci I don't see any attachment but I do see content from the Coppertone site, but it looks like the hitslabs site cannot pull the coppertone stylesheets so it all just looks like plain text.
I have changed the default ad to be the Pet Basics page. Please let me know if this is any better.

**Comment by ptavolacci** [comment]
Fine! That works and is more timely for our initiatives. Thanks for the quick response
