### ISSUE TITLE
As internal marketing we need a more detailed About Us page

### ISSUE THREAD

**Issue by ptavolacci** [Hitslabs/hitslabs#69]
Change the "Our Business" section at http://www.hitslabs.com/about to the following:

HITSLab LLC is a Delaware and Connecticut Registered entity that owns and operates the following businesses

Health Information Technology System
Consultancy
Detailing and Samples
Health Data Integration Services

The four items above should Link to subpages that have the following descriptions:
Health Information Technology System> A free and anonymous platform for patients, pet owners. medical professionals, employees, employers and others supported by highly contextual advertising channels. Subscriptions are also available. The platform, hosted at www.hitslabs.com provides valuable workflow solutions and ways to aggregrate records

Consultancy>Implementation and Optimization of human and animal electronic health records systems

Detailing and Samples>Consumer Health Product distribution for data collection for market research or marketing purposes

Health Data Integration Services>Contract Services for the integration of disparate systems to achieve interoperability 

Change "noticed" to "determined" under Our Story section

Add December 2016 "Animal health beta test begins" under Milestones

**Comment by skagels-hitslab** [comment]
@sanpinrin1 Hi Mohamed.
Just checking in on this story. Do you think you will be done soon? We would like to deploy these pages as soon as possible.

Thanks,
Scott

**Comment by sanpinrin1** [comment]
I am busy all day today. I will definitely finish it tomorrow

Sent from my iPhone

On Dec 6, 2016, at 10:06 AM, Scott Kagels <notifications@github.com<mailto:notifications@github.com>> wrote:


@sanpinrin1<https://github.com/sanpinrin1> Hi Mohamed.
Just checking in on this story. Do you think you will be done soon? We would like to deploy these pages as soon as possible.

Thanks,
Scott

-

**Comment by ptavolacci** [comment]
Thanks, Mohamed! Looking forward to it and will be meeting with some
Marketing Strategists who would like to see this so we can work together.

Paul

Paul M Tavolacci <https://www.linkedin.com/in/paul-tavolacci-mba-b4b0866>
Hitslab LLC
30 Hilton Street
Darien, CT 06820
415-595-4625 Direct
www.hitslabs.com

**Comment by skagels-hitslab** [comment]
@Mohamed, thanks for the fixes. I just made a few minor tweaks.
